services:
  postgres:
    image: postgres:latest
    restart: on-failure
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data
volumes: {}
