services:
  postgres:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: on-failure
  mysql:
    image: mysql:latest
    restart: on-failure
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DB: mysql
volumes:
  postgres_data: null
